FROM debian:12.2 as BASE
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y build-essential cmake
RUN apt-get install -y libopenblas-openmp-dev
RUN apt-get autoclean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
